### PR TITLE
Added Hello World using recursion

### PR DESCRIPTION
**Pull request by slingky814**

### CODE REVIEW

**Comment by slingky814** [comment]
Hi this is my first time contributing to an actual project.

**Comment by Goku-kun** [comment]
Hey @slingky814 
You should be very proud of yourself because you've now contributed to an actual open source project. I'm approving this pull request. Keep coding and making more amazing programs!

**Review by Goku-kun — APPROVED** [review]
Approving the pull request in this review.

**Comment by slingky814** [comment]
Thank you so much. I wish you the best!

**Pull request merged**
