### PR TITLE
add using excel

### PR DESCRIPTION
**Pull request by Zrmikstri**

### CODE REVIEW

**Comment by Goku-kun** [comment]
Hello @Zrmikstri. Thank you for creating this pull request.

Could you please share the adjoining 'hello_world.xls' file as well?

**Comment by Zrmikstri** [comment]
> Sure, thanks for reviewing my pull request. Here's the xls files.
[hello_world.xls](https://github.com/Goku-kun/1000-ways-to-print-hello-world-in-python/files/7603740/hello_world.xls)

**Review by Goku-kun — APPROVED** [review]
Alright. This is good work. I'm approving it. Thank you for your contribution.

**Comment by Zrmikstri** [comment]
Thank you very much!

**Pull request merged**
