### PR TITLE
2 another way to say hello world 

### PR DESCRIPTION
**Pull request by dictionary243**
first one is saying hello using scrapping and downloading and then running .py file 
second one is using sub process module .

### CODE REVIEW

**Review by Goku-kun — CHANGES_REQUESTED** [review]
Hello @dictionary243 
Beautifully done. This is one of the most comprehensive "Hello, World!" program I've ever seen. Good work there!

Additionally, I'd like you to make file rename changes so that these beautiful programs become more consistent with the rest of the lot.

Kindly rename the file "Hardest-hello.py" to "using-repo-programs.py" and the "Subprocess-hello.py" to "using-subprocess.py" and make a new pull request.

With these changes done, I'll approve the pull request. 

Thank you for the contribution. 🌟

**Comment by dictionary243** [comment]
yeah I am doing it ,and yeah do one thing there is a file called 'using binary' rename it to 'using -binary.py' so that my code can detect that file also and will run that.

**Comment by dictionary243** [comment]
I Think Now You can Merge It.

**Review by Goku-kun — APPROVED** [review]
Approving the merge. 

Thanks for contributing!

**Pull request merged**
